version: '3.8'

services:
  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: mysql-enterprise
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - ca-network

  # MongoDB Cluster
  mongo-db:
    image: mongo:latest
    container_name: mongo-telemetry
    restart: always
    volumes:
      - ./mongo_data:/data/db
    networks:
      - ca-network

  # The Backend API
  backend:
    build: ./be
    container_name: city-archive-api
    restart: always
    depends_on:
      - mysql-db
      - mongo-db
    environment:
      - MYSQL_HOST=mysql-db
      - MONGO_URI=mongodb://mongo-db:27017/telemetry
      - PORT=5000
    networks:
      - ca-network

  # Reverse Proxy (Handles HTTPS automatically)
  reverse-proxy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ca-network

networks:
  ca-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: